FROM node:24.19.0-bookworm-slim AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN --mount=type=secret,id=proxy_ca \
    if [ -f /run/secrets/proxy_ca ]; then \
        NODE_EXTRA_CA_CERTS=/run/secrets/proxy_ca npm ci --strict-ssl=true; \
    else \
        npm ci --strict-ssl=true; \
    fi

FROM node:24.19.0-bookworm-slim AS build
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_YGGDRASIL_API_ROOT
ARG NEXT_PUBLIC_ICONFONT_SYMBOL_URL
ARG NEXT_PUBLIC_ICONFONT_SYMBOL_INTEGRITY
ARG NEXT_PUBLIC_CSP_CONNECT_ORIGINS
ARG NEXT_PUBLIC_CSP_IMAGE_ORIGINS
ARG NEXT_PUBLIC_CSP_MEDIA_ORIGINS
ARG NEXT_PUBLIC_CSP_FONT_ORIGINS
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_YGGDRASIL_API_ROOT=$NEXT_PUBLIC_YGGDRASIL_API_ROOT
ENV NEXT_PUBLIC_ICONFONT_SYMBOL_URL=$NEXT_PUBLIC_ICONFONT_SYMBOL_URL
ENV NEXT_PUBLIC_ICONFONT_SYMBOL_INTEGRITY=$NEXT_PUBLIC_ICONFONT_SYMBOL_INTEGRITY
ENV NEXT_PUBLIC_CSP_CONNECT_ORIGINS=$NEXT_PUBLIC_CSP_CONNECT_ORIGINS
ENV NEXT_PUBLIC_CSP_IMAGE_ORIGINS=$NEXT_PUBLIC_CSP_IMAGE_ORIGINS
ENV NEXT_PUBLIC_CSP_MEDIA_ORIGINS=$NEXT_PUBLIC_CSP_MEDIA_ORIGINS
ENV NEXT_PUBLIC_CSP_FONT_ORIGINS=$NEXT_PUBLIC_CSP_FONT_ORIGINS
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:24.19.0-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
RUN groupadd --system --gid 1001 nodejs && useradd --system --uid 1001 --gid nodejs nextjs
COPY --from=build --chown=nextjs:nodejs /app/public ./public
COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]
