"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { apiRequest } from "../_lib/api";
import { supportedLocales, useI18n } from "../_lib/i18n-provider";
import { MarkdownRenderer } from "./markdown-renderer";

type ReportRow = { id: string; targetType: string; targetId: string; reasonCode: string; status: string; reporterName: string; createdAt: string };
type ReportDetail = ReportRow & { detail: string; customReason: string; reporterId: string; targetAuthorId?: string; targetAuthorName?: string; snapshot?: Record<string, unknown>; evidence: Array<Record<string, unknown>>; reviews: Array<Record<string, unknown>>; actions: Array<Record<string, unknown>>; relatedReports: Array<Record<string, unknown>> };
type BanReason = { code: string; label: string; sortOrder: number };

export function UnifiedReportAdminPanel({ token }: { token: string }) {
  const { locale, t } = useI18n();
  const banReasons = useBanReasons(token, locale);
  const [status, setStatus] = useState("pending");
  const [items, setItems] = useState<ReportRow[]>([]);
  const [detail, setDetail] = useState<ReportDetail>();
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    try { const value = await apiRequest<{ items: ReportRow[] }>(`/api/v1/admin/reports?status=${encodeURIComponent(status)}`, {}, token); setItems(value.items); setMessage(""); }
    catch (error) { setMessage(errorMessage(error)); }
  }, [status, token]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function select(id: string) { try { setDetail(await apiRequest<ReportDetail>(`/api/v1/admin/reports/${id}`, {}, token)); } catch (error) { setMessage(errorMessage(error)); } }
  async function claim() { if (!detail) return; setBusy(true); try { await apiRequest(`/api/v1/admin/reports/${detail.id}/claim`, { method: "POST", body: "{}" }, token); await select(detail.id); await load(); } catch (error) { setMessage(errorMessage(error)); } finally { setBusy(false); } }
  async function resolve(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!detail) return;
    const form = new FormData(event.currentTarget); setBusy(true);
    try {
      await apiRequest(`/api/v1/admin/reports/${detail.id}/resolve`, { method: "POST", body: JSON.stringify({
        conclusion: form.get("conclusion"), note: form.get("note"), deleteTarget: form.get("deleteTarget") === "on",
        banUserId: String(form.get("banUserId") || ""), banReasonCode: String(form.get("banReasonCode") || ""),
        banCustomReason: String(form.get("banCustomReason") || ""), publicRecordMarkdown: String(form.get("publicRecordMarkdown") || ""),
        idempotencyKey: crypto.randomUUID(),
      }) }, token);
      setDetail(undefined); await load();
    } catch (error) { setMessage(errorMessage(error)); } finally { setBusy(false); }
  }
  async function openEvidence(id: unknown) {
    try { const value = await apiRequest<{ url: string }>(`/api/v1/reports/evidence/${String(id)}/access`, { method: "POST", body: "{}" }, token); window.open(value.url, "_blank", "noopener,noreferrer"); }
    catch (error) { setMessage(errorMessage(error)); }
  }
  return <AdminSplit title={t("admin.governance.reports")} message={message} left={<>
    <select className="field mb-3" value={status} onChange={(event) => { setStatus(event.target.value); setDetail(undefined); }}>{["pending", "in_review", "resolved_valid", "resolved_invalid"].map((value) => <option key={value} value={value}>{value}</option>)}</select>
    <div className="grid gap-2">{items.map((item) => <button className="rounded-lg border border-[var(--line)] p-3 text-left hover:border-[var(--accent)]" key={item.id} type="button" onClick={() => void select(item.id)}><strong className="block">{item.targetType} · {item.reasonCode}</strong><span className="mt-1 block text-xs text-[var(--muted)]">{item.reporterName} · {new Date(item.createdAt).toLocaleString()}</span></button>)}</div>
  </>} right={!detail ? <Empty text={t("admin.governance.selectReport")} /> : <div className="space-y-5">
    <div><p className="text-xs font-black uppercase text-[var(--accent)]">{detail.status}</p><h3 className="mt-1 text-xl font-black">{detail.targetType} · {detail.targetId}</h3><p className="mt-2 text-sm text-[var(--muted)]">{detail.reasonCode}{detail.customReason ? ` · ${detail.customReason}` : ""}</p><p className="mt-3 whitespace-pre-wrap">{detail.detail}</p></div>
    <section><h4 className="font-black">{t("admin.governance.reportSnapshot")}</h4><pre className="mt-2 max-h-72 overflow-auto rounded-lg bg-[var(--panel-subtle)] p-3 text-xs">{detail.snapshot ? JSON.stringify(detail.snapshot, null, 2) : t("admin.governance.snapshotRestricted")}</pre></section>
    <section><h4 className="font-black">{t("admin.governance.evidence")}</h4><div className="mt-2 flex flex-wrap gap-2">{detail.evidence?.map((item) => <button className="button-secondary focus-ring" key={String(item.public_id)} disabled={item.status === "deleted"} type="button" onClick={() => void openEvidence(item.public_id)}>{String(item.original_name)} · {String(item.scan_status)}</button>)}</div></section>
    {detail.status === "pending" ? <button className="button-secondary focus-ring" disabled={busy} type="button" onClick={() => void claim()}>{t("admin.governance.claim")}</button> : null}
    {detail.status === "pending" || detail.status === "in_review" ? <form className="grid gap-3 rounded-xl border border-[var(--line)] p-4" onSubmit={resolve}><select className="field" name="conclusion"><option value="valid">{t("admin.governance.valid")}</option><option value="invalid">{t("admin.governance.invalid")}</option></select><textarea className="field min-h-24" name="note" placeholder={t("admin.governance.reviewNote")} /><label className="flex gap-2 font-bold"><input name="deleteTarget" type="checkbox" />{t("admin.governance.deleteTarget")}</label><input className="field" name="banUserId" placeholder={t("admin.governance.banUserId")} /><BanReasonSelect items={banReasons} name="banReasonCode" required={false} /><input className="field" name="banCustomReason" placeholder={t("admin.governance.customReason")} /><textarea className="field min-h-24" name="publicRecordMarkdown" placeholder={t("admin.governance.publicRecord")} /><button className="button-primary focus-ring" disabled={busy} type="submit">{t("admin.governance.resolve")}</button></form> : null}
  </div>} />;
}

type BanRow = { id: string; userId: string; username: string; reasonCode: string; customReason: string; status: string; startsAt: string; endsAt?: string };
export function BanAdminPanel({ token }: { token: string }) {
  const { locale, t } = useI18n(); const [items, setItems] = useState<BanRow[]>([]); const [message, setMessage] = useState(""); const banReasons = useBanReasons(token, locale);
  const load = useCallback(() => apiRequest<{ items: BanRow[] }>("/api/v1/admin/bans?limit=100", {}, token).then((value) => setItems(value.items)).catch((error) => setMessage(errorMessage(error))), [token]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const element = event.currentTarget; const form = new FormData(element); try { await apiRequest("/api/v1/admin/bans", { method: "POST", body: JSON.stringify({ userId: form.get("userId"), reasonCode: form.get("reasonCode"), customReason: form.get("customReason"), publicRecordMarkdown: form.get("publicRecordMarkdown"), internalNote: form.get("internalNote"), endsAt: form.get("endsAt") ? new Date(String(form.get("endsAt"))).toISOString() : null }) }, token); element.reset(); await load(); } catch (error) { setMessage(errorMessage(error)); } }
  async function revoke(id: string) { const reason = window.prompt(t("admin.governance.revokeReason")); if (!reason) return; try { await apiRequest(`/api/v1/admin/bans/${id}/revoke`, { method: "POST", body: JSON.stringify({ reason }) }, token); await load(); } catch (error) { setMessage(errorMessage(error)); } }
  return <section><PanelHeader title={t("admin.governance.bans")} description={t("admin.governance.bansDescription")} />{message ? <Notice text={message} /> : null}<form className="mt-5 grid gap-3 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-5 md:grid-cols-2" onSubmit={create}><input className="field" name="userId" required placeholder={t("admin.governance.banUserId")} /><BanReasonSelect items={banReasons} name="reasonCode" required /><input className="field" name="customReason" placeholder={t("admin.governance.customReason")} /><input className="field" name="endsAt" type="datetime-local" /><textarea className="field min-h-24 md:col-span-2" name="publicRecordMarkdown" placeholder={t("admin.governance.publicRecord")} /><textarea className="field min-h-20 md:col-span-2" name="internalNote" placeholder={t("admin.governance.internalNote")} /><button className="button-primary focus-ring md:col-span-2" type="submit">{t("admin.governance.createBan")}</button></form><div className="mt-5 grid gap-3">{items.map((item) => <article className="rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4" key={item.id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{item.username}</strong><p className="mt-1 text-sm text-[var(--muted)]">{item.reasonCode}{item.customReason ? ` · ${item.customReason}` : ""} · {item.status}</p></div><div className="flex gap-2"><Link className="button-secondary focus-ring" href={`/site-affairs/blackroom/${item.id}`}>{t("admin.governance.publicView")}</Link>{item.status !== "released" ? <button className="button-secondary focus-ring" type="button" onClick={() => void revoke(item.id)}>{t("admin.governance.revoke")}</button> : null}</div></div></article>)}</div></section>;
}

type AboutDraft = { locale: string; title: string; bodyMarkdown: string; status: string; revision: number };
export function AboutAdminPanel({ token }: { token: string }) {
  const { locale: currentLocale, t } = useI18n(); const [locale, setLocale] = useState<string>(currentLocale); const [draft, setDraft] = useState<AboutDraft>({ locale, title: "", bodyMarkdown: "", status: "draft", revision: 0 }); const [preview, setPreview] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(() => apiRequest<AboutDraft>(`/api/v1/admin/site-affairs/about/${locale}`, {}, token).then(setDraft).catch((error) => setMessage(errorMessage(error))), [locale, token]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function save(publish: boolean) { try { await apiRequest(`/api/v1/admin/site-affairs/about/${locale}`, { method: "PUT", body: JSON.stringify({ title: draft.title, bodyMarkdown: draft.bodyMarkdown, publish }) }, token); setMessage(t("admin.governance.saved")); await load(); } catch (error) { setMessage(errorMessage(error)); } }
  return <section><PanelHeader title={t("admin.governance.about")} description={t("admin.governance.aboutDescription")} />{message ? <Notice text={message} /> : null}<div className="mt-5 flex flex-wrap gap-2"><select className="field w-auto" value={locale} onChange={(event) => setLocale(event.target.value)}>{supportedLocales.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select><button className="button-secondary focus-ring" type="button" onClick={() => setPreview((value) => !value)}>{t("admin.governance.preview")}</button><button className="button-secondary focus-ring" type="button" onClick={() => void save(false)}>{t("admin.governance.saveDraft")}</button><button className="button-primary focus-ring" type="button" onClick={() => void save(true)}>{t("admin.governance.publish")}</button></div><input className="field mt-4" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder={t("admin.governance.titleField")} /><textarea className="field mt-4 min-h-[420px] font-mono" value={draft.bodyMarkdown} onChange={(event) => setDraft({ ...draft, bodyMarkdown: event.target.value })} />{preview ? <div className="markdown-preview mt-5 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-5"><MarkdownRenderer emptyText="" markdown={draft.bodyMarkdown} /></div> : null}</section>;
}

type AdminChangelog = { id: string; changeDate: string; status: string; translations: Record<string, { title: string; bodyMarkdown: string }> };
export function SiteChangelogAdminPanel({ token }: { token: string }) {
  const { locale: currentLocale, t } = useI18n(); const [items, setItems] = useState<AdminChangelog[]>([]); const [editing, setEditing] = useState(""); const [locale, setLocale] = useState<string>(currentLocale); const [date, setDate] = useState(today()); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [publish, setPublish] = useState(false); const [preview, setPreview] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(() => apiRequest<{ items: AdminChangelog[] }>("/api/v1/admin/site-affairs/changelogs", {}, token).then((value) => setItems(value.items)).catch((error) => setMessage(errorMessage(error))), [token]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  function edit(item: AdminChangelog) { setEditing(item.id); setDate(item.changeDate.slice(0, 10)); setPublish(item.status === "published"); const value = item.translations[locale] || Object.values(item.translations)[0]; setTitle(value?.title || ""); setBody(value?.bodyMarkdown || ""); }
  async function save(event: FormEvent) { event.preventDefault(); const path = editing ? `/api/v1/admin/site-affairs/changelogs/${editing}` : "/api/v1/admin/site-affairs/changelogs"; try { await apiRequest(path, { method: editing ? "PUT" : "POST", body: JSON.stringify({ changeDate: date, locale, title, bodyMarkdown: body, publish }) }, token); setEditing(""); setTitle(""); setBody(""); await load(); setMessage(t("admin.governance.saved")); } catch (error) { setMessage(errorMessage(error)); } }
  return <section><PanelHeader title={t("admin.governance.changelogs")} description={t("admin.governance.changelogsDescription")} />{message ? <Notice text={message} /> : null}<div className="mt-5 grid gap-5 xl:grid-cols-[360px_1fr]"><div className="grid content-start gap-2">{items.map((item) => <button className="rounded-lg border border-[var(--line)] bg-[var(--panel)] p-3 text-left hover:border-[var(--accent)]" key={item.id} type="button" onClick={() => edit(item)}><strong>{item.changeDate.slice(0, 10)}</strong><span className="ml-2 text-xs text-[var(--muted)]">{item.status}</span><p className="mt-1 truncate text-sm">{Object.values(item.translations)[0]?.title}</p></button>)}</div><form className="grid gap-3 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-5" onSubmit={save}><div className="flex flex-wrap gap-2"><input className="field w-auto" required type="date" value={date} onChange={(event) => setDate(event.target.value)} /><button className="button-secondary focus-ring" type="button" onClick={() => setDate(today())}>{t("admin.governance.today")}</button><select className="field w-auto" value={locale} onChange={(event) => setLocale(event.target.value)}>{supportedLocales.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select></div><input className="field" required value={title} onChange={(event) => setTitle(event.target.value)} placeholder={t("admin.governance.titleField")} /><textarea className="field min-h-72 font-mono" required value={body} onChange={(event) => setBody(event.target.value)} /><label className="flex gap-2 font-bold"><input checked={publish} type="checkbox" onChange={(event) => setPublish(event.target.checked)} />{t("admin.governance.publish")}</label><div className="flex gap-2"><button className="button-secondary focus-ring" type="button" onClick={() => setPreview((value) => !value)}>{t("admin.governance.preview")}</button><button className="button-primary focus-ring" type="submit">{editing ? t("common.save") : t("common.create")}</button></div>{preview ? <div className="markdown-preview rounded-lg border border-[var(--line)] p-4"><MarkdownRenderer emptyText="" markdown={body} /></div> : null}</form></div></section>;
}

type SeedConfig = { enabled: boolean; projectTypes: string[]; batchSize: number; dailyLimit: number; minimumDownloads: number; intervalSeconds: number; maxConcurrency: number; aiDailyTokenBudget: number; autoSubmitReview: boolean; lastRunAt?: string; nextRunAt?: string };
export function SeedCrawlerAdminPanel({ token }: { token: string }) {
  const { t } = useI18n(); const [config, setConfig] = useState<SeedConfig>(); const [runs, setRuns] = useState<Array<Record<string, unknown>>>([]); const [candidates, setCandidates] = useState<Array<Record<string, unknown>>>([]); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { const [cfg, runData, candidateData] = await Promise.all([apiRequest<{ config: SeedConfig }>("/api/v1/admin/seed-crawler", {}, token), apiRequest<{ items: Array<Record<string, unknown>> }>("/api/v1/admin/seed-crawler/runs", {}, token), apiRequest<{ items: Array<Record<string, unknown>> }>("/api/v1/admin/seed-crawler/candidates", {}, token)]); setConfig(cfg.config); setRuns(runData.items); setCandidates(candidateData.items); } catch (error) { setMessage(errorMessage(error)); } }, [token]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function save() { if (!config) return; try { await apiRequest("/api/v1/admin/seed-crawler", { method: "PUT", body: JSON.stringify(config) }, token); await load(); setMessage(t("admin.governance.saved")); } catch (error) { setMessage(errorMessage(error)); } }
  async function run(dryRun: boolean) { try { await apiRequest("/api/v1/admin/seed-crawler/runs", { method: "POST", body: JSON.stringify({ dryRun }) }, token); await load(); } catch (error) { setMessage(errorMessage(error)); } }
  if (!config) return <Empty text={message || t("common.loading")} />;
  return <section><PanelHeader title={t("admin.automation.seedCrawler")} description={t("admin.automation.seedCrawlerDescription")} />{message ? <Notice text={message} /> : null}<div className="mt-5 grid gap-4 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-5 sm:grid-cols-2 lg:grid-cols-4"><Toggle label={t("common.enabled")} checked={config.enabled} onChange={(value) => setConfig({ ...config, enabled: value })} /><Toggle label={t("admin.automation.autoSubmit")} checked={config.autoSubmitReview} onChange={(value) => setConfig({ ...config, autoSubmitReview: value })} />{(["batchSize", "dailyLimit", "minimumDownloads", "intervalSeconds", "maxConcurrency", "aiDailyTokenBudget"] as const).map((key) => <label className="grid gap-1 text-sm font-bold" key={key}>{key}<input className="field" min={0} type="number" value={config[key]} onChange={(event) => setConfig({ ...config, [key]: Number(event.target.value) })} /></label>)}<label className="grid gap-2 text-sm font-bold sm:col-span-2 lg:col-span-4">{t("admin.automation.projectTypes")}<span className="flex flex-wrap gap-3">{["mod", "plugin", "shader_pack", "resource_pack"].map((type) => <label className="flex gap-2" key={type}><input checked={config.projectTypes.includes(type)} type="checkbox" onChange={(event) => setConfig({ ...config, projectTypes: event.target.checked ? [...config.projectTypes, type] : config.projectTypes.filter((value) => value !== type) })} />{type}</label>)}</span></label><div className="flex flex-wrap gap-2 sm:col-span-2 lg:col-span-4"><button className="button-primary focus-ring" type="button" onClick={() => void save()}>{t("common.save")}</button><button className="button-secondary focus-ring" type="button" onClick={() => void run(true)}>{t("admin.automation.dryRun")}</button><button className="button-secondary focus-ring" type="button" onClick={() => void run(false)}>{t("admin.automation.run")}</button></div></div><RecordTable title={t("admin.automation.runs")} items={runs} /><RecordTable title={t("admin.automation.candidates")} items={candidates} /></section>;
}

export function ProjectAutomationAdminPanel({ token }: { token: string }) { const { t } = useI18n(); const [data, setData] = useState<{ runs: Array<Record<string, unknown>>; settings: Array<Record<string, unknown>> }>({ runs: [], settings: [] }); const [message, setMessage] = useState(""); const load = useCallback(() => apiRequest<typeof data>("/api/v1/admin/project-auto-updates", {}, token).then(setData).catch((error) => setMessage(errorMessage(error))), [token]); useEffect(() => { queueMicrotask(() => void load()); }, [load]); return <section><PanelHeader title={t("admin.automation.projectUpdates")} description={t("admin.automation.projectUpdatesDescription")} />{message ? <Notice text={message} /> : null}<button className="button-secondary focus-ring mt-4" type="button" onClick={() => void load()}>{t("common.refresh")}</button><RecordTable title={t("admin.automation.settings")} items={data.settings} /><RecordTable title={t("admin.automation.runs")} items={data.runs} /></section>; }

function AdminSplit({ title, message, left, right }: { title: string; message: string; left: React.ReactNode; right: React.ReactNode }) { return <section><PanelHeader title={title} description="" />{message ? <Notice text={message} /> : null}<div className="mt-5 grid gap-5 xl:grid-cols-[360px_1fr]"><div className="max-h-[72vh] overflow-auto rounded-xl border border-[var(--line)] bg-[var(--panel)] p-3">{left}</div><div className="min-w-0 rounded-xl border border-[var(--line)] bg-[var(--panel)] p-5">{right}</div></div></section>; }
function PanelHeader({ title, description }: { title: string; description: string }) { return <header><h2 className="text-2xl font-black">{title}</h2>{description ? <p className="mt-2 max-w-4xl text-sm leading-6 text-[var(--muted)]">{description}</p> : null}</header>; }
function Notice({ text }: { text: string }) { return <p className="mt-4 rounded-lg border border-[var(--line)] bg-[var(--panel)] p-3 text-sm font-bold" role="status">{text}</p>; }
function Empty({ text }: { text: string }) { return <div className="grid min-h-48 place-items-center text-center font-bold text-[var(--muted)]">{text}</div>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2 font-bold"><input checked={checked} type="checkbox" onChange={(event) => onChange(event.target.checked)} />{label}</label>; }
function BanReasonSelect({ items, name, required }: { items: BanReason[]; name: string; required: boolean }) { return <select className="field" defaultValue="" name={name} required={required}><option value="">—</option>{items.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select>; }
function useBanReasons(token: string, locale: string) { const [items, setItems] = useState<BanReason[]>([]); useEffect(() => { let active = true; void apiRequest<{ items: BanReason[] }>(`/api/v1/admin/ban-reasons?locale=${encodeURIComponent(locale)}`, {}, token).then((value) => { if (active) setItems(value.items); }).catch(() => { if (active) setItems([]); }); return () => { active = false; }; }, [locale, token]); return items; }
function RecordTable({ title, items }: { title: string; items: Array<Record<string, unknown>> }) { return <section className="mt-6"><h3 className="text-lg font-black">{title}</h3><div className="mt-3 overflow-x-auto rounded-xl border border-[var(--line)]"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[var(--panel-subtle)]"><tr>{Object.keys(items[0] || {}).map((key) => <th className="px-3 py-2" key={key}>{key}</th>)}</tr></thead><tbody>{items.map((item, index) => <tr className="border-t border-[var(--line)]" key={String(item.id || item.public_id || index)}>{Object.keys(items[0] || {}).map((key) => <td className="max-w-72 truncate px-3 py-2" title={display(item[key])} key={key}>{display(item[key])}</td>)}</tr>)}</tbody></table>{items.length === 0 ? <p className="p-6 text-center text-[var(--muted)]">—</p> : null}</div></section>; }
function display(value: unknown) { return typeof value === "object" && value !== null ? JSON.stringify(value) : String(value ?? "—"); }
function errorMessage(value: unknown) { return value instanceof Error ? value.message : String(value); }
function today() { return new Date().toISOString().slice(0, 10); }
