import en from "./en-US";
const de = {
  ...en,
  common: { ...en.common, home: "Start", login: "Anmelden", register: "Registrieren", logout: "Abmelden", admin: "Admin", save: "Speichern", delete: "Löschen", language: "Sprache" },
  home: { ...en.home, title: "Ressourcen-Navigation" },
  skins: { ...en.skins, title: "Skin-Bibliothek", subtitle: "Community-Skins und Umhänge durchsuchen, sammeln und Spielerprofilen zuweisen.", upload: "Aussehen hochladen", kindSkin: "Skin", kindCape: "Umhang", playerProfiles: "Spielerprofile", wardrobe: "Meine Garderobe", launcherLogin: "Drittanbieter-Launcher-Anmeldung", saveProfile: "Profil speichern", deleteProfile: "Profil löschen", visibilityPublic: "Öffentlich", visibilityUnlisted: "Nicht gelistet", visibilityPrivate: "Privat", copyAddress: "Kopieren", copied: "Kopiert" },
  assetEditor: { ...en.assetEditor, back: "Zurück zu den Details", skinTitle: "Skin bearbeiten", blueprintTitle: "Bauplan bearbeiten", submit: "Änderungen einreichen", name: "Name", introduction: "Beschreibung", tags: "Tags", visibility: "Sichtbarkeit", visibilityPublic: "Öffentlich", visibilityUnlisted: "Nicht gelistet", visibilityPrivate: "Privat", armModel: "Armmodell", modelClassic: "Klassisch", modelSlim: "Schmal", reason: "Änderungsübersicht", loginRequired: "Bitte vor dem Bearbeiten anmelden.", submitted: "Eingereicht. Prüfpflichtige Sprachversionen werden nach der Freigabe veröffentlicht.", saveFailed: "Änderungen konnten nicht gespeichert werden.", loadFailed: "Editor-Daten konnten nicht geladen werden.", defaultReason: "Lokalisierte Inhalte bearbeitet" },
  mods: { ...en.mods, submission: { ...en.mods.submission, defaultLocale: "Standard-Inhaltssprache", galleryUploadFailed: "Das Galeriebild konnte nicht hochgeladen werden.", modIds: { title: "Mod-IDs", hint: "Aktuelle und frühere IDs können je Minecraft-Version registriert werden. Die primäre ID dient der kanonischen Anzeige; alle IDs verweisen auf dieselbe globale Ressourcenidentität.", add: "ID hinzufügen", identifier: "Mod-ID", minecraftVersions: "Unterstützte Minecraft-Versionen", allSupportedVersions: "Alle unterstützten Minecraft-Versionen", primary: "Primäre ID" }, sections: { ...en.mods.submission.sections, gallery: "Galerie", galleryHint: "Bilder werden direkt in das private OSS hochgeladen und zusammen mit dieser vollständigen Mod-Revision geprüft." }, actions: { ...en.mods.submission.actions, uploadGallery: "Galeriebilder hochladen", uploadingGallery: "Wird hochgeladen…" } } },
  catalogEditor: { ...en.catalogEditor },
  modContent: { ...en.modContent, templates: { ...en.modContent.templates, loot_table: "Beutetabellen", game_setting: "Spieleinstellungen" } },
  resourceEditor: {
    ...en.resourceEditor,
    catalogShort: "Ressourcen", catalogTitle: "Globaler Ressourcenkatalog", catalogDescription: "Gegenstände, Blöcke, Flüssigkeiten, Chemikalien und weitere Spielressourcen durchsuchen und manuell pflegen. Importe dienen nur als Hilfe.",
    search: "Ressourcen suchen", searchPlaceholder: "Lokalisierter Name oder Ressourcen-ID", allKinds: "Alle Typen", allRegistries: "Alle Namensräume", empty: "Keine passenden Ressourcen.", globalResource: "Globale Ressource",
    create: "Ressource erstellen", edit: "Ressource bearbeiten", back: "Zurück zu den Ressourcen", description: "Stabile Identität, mehrsprachige Inhalte, private OSS-Bilder und strukturierte Spieleigenschaften pflegen. Jede Änderung wird geprüft und im Benutzerverlauf erfasst.",
    validationRequired: "Ressourcentyp, kanonische ID und einen Namen in der Standardsprache eingeben.", archiveConfirm: "Diese Ressource archivieren?", imageOnly: "Für Symbol und Render-Vorschau muss eine Bilddatei gewählt werden.", uploadFailed: "Das Bild konnte nicht hochgeladen werden.",
    kind: "Ressourcentyp", ownerMod: "Website-ID des Mod-Eigentümers", ownerModPlaceholder: "Optional, z. B. create", assetsTitle: "Ressourcenbilder", assetsDescription: "Der Browser lädt Bilder direkt in das private OSS hoch; die Datei-IDs werden mit dieser Revision geprüft.", icon: "Symbol", render: "Renderbild", iconEmpty: "Kein Symbol hochgeladen", renderEmpty: "Kein Renderbild hochgeladen", upload: "Bild hochladen", uploading: "Wird hochgeladen…", assetRecords: "Verknüpfte Dateien", iconFileId: "Symbol-Datei-ID", renderFileId: "Renderbild-Datei-ID",
    physicalTitle: "Block- und Physikeigenschaften", physicalDescription: "Physikalisches Verhalten von Blöcken und Weltressourcen.", hardness: "Härte", explosionResistance: "Explosionswiderstand", friction: "Reibung", speedFactor: "Bewegungsfaktor", jumpFactor: "Sprungfaktor", lightLevel: "Lichtstufe", requiresCorrectTool: "Richtiges Werkzeug erforderlich", randomTicks: "Zufällige Ticks", replaceable: "Ersetzbar", air: "Als Luft behandelt",
    toolTitle: "Werkzeugeigenschaften", toolDescription: "Abbau, Kampf, Haltbarkeit, Stufe, Reparatur und Verzauberung.", toolType: "Werkzeugtyp", tier: "Werkzeugstufe", repairTag: "Reparaturmaterial-Tag", durability: "Haltbarkeit", miningSpeed: "Abbaugeschwindigkeit", attackDamage: "Angriffsschaden", attackSpeed: "Angriffsgeschwindigkeit", enchantability: "Verzauberbarkeit", harvestLevel: "Abbaustufe",
    renderTitle: "Rendereigenschaften", renderDescription: "Renderer, Modell und Transformation unabhängig vom Vorschaubild beschreiben.", renderMode: "Rendermodus", unset: "Nicht gesetzt", model: "Modell", modelResourceId: "Modellressourcen-ID", renderer: "Renderer-ID", scale: "Skalierung", rotation: "Drehung (X/Y/Z)", translation: "Verschiebung (X/Y/Z)",
    fluidTitle: "Flüssigkeitseigenschaften", fluidDescription: "Physikalische und visuelle Eigenschaften von Flüssigkeiten.", chemicalTitle: "Chemikalieneigenschaften", chemicalDescription: "Eigenschaften von Gasen, Schlämmen, Pigmenten und anderen Chemikalien.", density: "Dichte", viscosity: "Viskosität", temperature: "Temperatur", luminosity: "Leuchtstärke", tint: "Farbton", gaseous: "Gasförmig",
    extensionTitle: "Mod-spezifische Erweiterungsdaten", extensionDescription: "Zukünftige oder Mod-spezifische Eigenschaften als JSON-Objekt ergänzen.", applyExtensions: "Erweiterungs-JSON anwenden", extensionInvalid: "Ein gültiges JSON-Objekt ohne reservierte Abschnittsnamen eingeben.",
  },
  contentTranslation: {
    ...en.contentTranslation,
    loading: "Inhaltssprache wird ermittelt…", aiBadge: "KI-übersetzt", humanCorrectedBadge: "Menschlich korrigiert", showingFallback: "Fallback-Inhalt auf {locale} wird angezeigt",
    freeInProgress: "KI-Übersetzung läuft · ohne tägliches Token-Kontingent", paidInProgress: "KI-Übersetzung läuft · nutzt das tägliche Token-Kontingent",
    paidExplanation: "Diesen Inhalt nach {locale} übersetzen und speichern. Dies nutzt dein tägliches KI-Token-Kontingent.", translate: "Übersetzen", requesting: "Wird angefordert…", loginToTranslate: "Zum Übersetzen anmelden", noPermission: "Übersetzung nicht verfügbar", readOnly: "Die Version {locale} ist nur für KI-Übersetzungen und nicht manuell bearbeitbar.", failed: "KI-Übersetzung fehlgeschlagen. Bitte später erneut versuchen.",
  },
  contentLanguage: {
    ...en.contentLanguage,
    title: "Inhaltssprachen", description: "Erste und zweite Sprache für lokalisierte Inhalte wählen. Unterstützte Sprachen sind bearbeitbar; andere gültige BCP-47-Sprachen werden als gespeicherte KI-Übersetzungen genutzt.",
    primary: "Erste Inhaltssprache", primaryHint: "Nach dieser Sprache wird zuerst gesucht; nicht unterstützte Sprachen sind reine Übersetzungsziele.", secondary: "Zweite Inhaltssprache", secondaryHint: "Wird verwendet, wenn die erste Sprache nicht verfügbar ist.",
    chineseFallbackHint: "Vereinfachtes und traditionelles Chinesisch greifen vor Englisch aufeinander zurück.", editablePrimary: "Bearbeitbare Sprache", translationOnlyPrimary: "Nur Übersetzung", save: "Sprachen speichern", saved: "Inhaltssprachen gespeichert.", required: "Erste und zweite Inhaltssprache eingeben.", loadFailed: "Inhaltssprachen konnten nicht geladen werden.", saveFailed: "Inhaltssprachen konnten nicht gespeichert werden.",
  },
  admin: { ...en.admin, title: "Admin-Konsole", i18n: "Mehrsprachigkeit", translationManager: "Übersetzungen" },
};
de.mods = { ...de.mods, detail: { ...de.mods.detail, downloads: {
  ...en.mods.detail.downloads,
  title: "Projektdateien", subtitle: "Minecraft-Version und Loader auswählen und Dateien direkt von Mcmods-cn, Modrinth oder CurseForge laden, ohne eine externe Projektseite zu öffnen.",
  minecraftVersion: "Minecraft-Version", all: "Alle", loader: "Loader", allLoaders: "Alle Loader", source: "Downloadquelle", allSources: "Alle Quellen", externalSources: "Externe Quellen",
  noFiles: "Keine Datei entspricht den Filtern.", loadFailed: "Projektdateien konnten nicht geladen werden.", downloadFailed: "Der Download konnte nicht vorbereitet werden.", downloadCount: "{count} Downloads", updated: "Aktualisiert am {date}", preparing: "Wird vorbereitet…", download: "Herunterladen",
  deleteConfirm: "{name} aus den Website-Downloads löschen?", deleteFailed: "Die Projektdatei konnte nicht gelöscht werden.", providerUnavailable: "{source} ist vorübergehend nicht verfügbar.",
  uploadTitle: "Veröffentlichungsdatei hochladen", uploadDescription: "Eine vertrauenswürdige Veröffentlichungsdatei für {project} hochladen. Dafür ist die projektspezifische Upload-Berechtigung erforderlich.", projectFile: "Veröffentlichungsdatei ({formats})", displayName: "Anzeigename", versionName: "Projektversion", gameVersions: "Minecraft-Versionen", loaders: "Loader", releaseChannel: "Veröffentlichungskanal",
  channels: { release: "Release", beta: "Beta", alpha: "Alpha" }, unsupportedFileFormat: "Bitte eine unterstützte Datei auswählen: {formats}.", metadataRequired: "Projektversion, Minecraft-Version und Loader sind erforderlich.", upload: "Datei hochladen", uploading: "Wird hochgeladen…", uploaded: "Die Datei wurde hochgeladen und wird nach bestandener Sicherheitsprüfung veröffentlicht.", uploadFailed: "Die Datei konnte nicht hochgeladen werden.",
} } };
export default de;
