import en from "./en-US";
const es = {
  ...en,
  common: { ...en.common, home: "Inicio", login: "Iniciar sesión", register: "Registrarse", logout: "Cerrar sesión", admin: "Admin", save: "Guardar", delete: "Eliminar", language: "Idioma" },
  home: { ...en.home, title: "Navegación de recursos" },
  skins: { ...en.skins, title: "Biblioteca de skins", subtitle: "Explora, guarda y equipa skins y capas de la comunidad en tus perfiles de jugador.", upload: "Subir apariencia", kindSkin: "Skin", kindCape: "Capa", playerProfiles: "Perfiles de jugador", wardrobe: "Mi armario", launcherLogin: "Inicio de sesión en lanzadores externos", saveProfile: "Guardar perfil", deleteProfile: "Eliminar perfil", visibilityPublic: "Público", visibilityUnlisted: "No listado", visibilityPrivate: "Privado", copyAddress: "Copiar", copied: "Copiado" },
  assetEditor: { ...en.assetEditor, back: "Volver a los detalles", skinTitle: "Editar skin", blueprintTitle: "Editar plano", submit: "Enviar cambios", name: "Nombre", introduction: "Introducción", tags: "Etiquetas", visibility: "Visibilidad", visibilityPublic: "Público", visibilityUnlisted: "No listado", visibilityPrivate: "Privado", armModel: "Modelo de brazos", modelClassic: "Clásico", modelSlim: "Delgado", reason: "Resumen de cambios", loginRequired: "Inicia sesión antes de editar.", submitted: "Cambios enviados. Las versiones de idioma que requieran revisión se publicarán tras su aprobación.", saveFailed: "No se pudieron guardar los cambios.", loadFailed: "No se pudieron cargar los datos de edición.", defaultReason: "Edición de contenido localizado" },
  mods: { ...en.mods, submission: { ...en.mods.submission, defaultLocale: "Idioma de contenido predeterminado", galleryUploadFailed: "No se pudo subir la imagen de la galería.", modIds: { title: "ID del mod", hint: "Registra los ID actuales e históricos según la versión de Minecraft. El ID principal se usa para la visualización canónica y todos apuntan a la misma identidad de recurso global.", add: "Añadir ID", identifier: "ID del mod", minimumVersion: "Versión mínima", maximumVersion: "Versión máxima", minimumPlaceholder: "Por ejemplo, 1.18", maximumPlaceholder: "Vacío significa sin límite", primary: "ID principal" }, sections: { ...en.mods.submission.sections, gallery: "Galería", galleryHint: "Las imágenes se suben directamente al OSS privado y se revisan junto con esta revisión completa del mod." }, actions: { ...en.mods.submission.actions, uploadGallery: "Subir imágenes de galería", uploadingGallery: "Subiendo…" } } },
  catalogEditor: { ...en.catalogEditor },
  modContent: { ...en.modContent, templates: { ...en.modContent.templates, loot_table: "Tablas de botín", game_setting: "Ajustes del juego" } },
  resourceEditor: {
    ...en.resourceEditor,
    catalogShort: "Recursos", catalogTitle: "Catálogo global de recursos", catalogDescription: "Explora y mantiene manualmente objetos, bloques, fluidos, sustancias químicas y otros recursos del juego. La importación solo sirve de ayuda.",
    search: "Buscar recursos", searchPlaceholder: "Nombre localizado o ID del recurso", allKinds: "Todos los tipos", allRegistries: "Todos los espacios de nombres", empty: "No hay recursos coincidentes.", globalResource: "Recurso global",
    create: "Crear recurso", edit: "Editar recurso", back: "Volver a recursos", description: "Mantén la identidad estable, el contenido multilingüe, las imágenes OSS privadas y las propiedades estructuradas. Cada cambio se revisa y registra.",
    validationRequired: "Introduce el tipo, el ID canónico y un nombre en el idioma predeterminado.", archiveConfirm: "¿Archivar este recurso?", imageOnly: "Selecciona una imagen para el icono o la vista renderizada.", uploadFailed: "No se pudo subir la imagen.",
    kind: "Tipo de recurso", ownerMod: "ID del sitio del mod propietario", ownerModPlaceholder: "Opcional, p. ej. create", assetsTitle: "Imágenes del recurso", assetsDescription: "El navegador sube las imágenes directamente al OSS privado; los ID de archivo se revisan con esta revisión.", icon: "Icono", render: "Imagen renderizada", iconEmpty: "Sin icono", renderEmpty: "Sin imagen renderizada", upload: "Subir imagen", uploading: "Subiendo…", assetRecords: "Archivos vinculados", iconFileId: "ID del archivo de icono", renderFileId: "ID del archivo renderizado",
    physicalTitle: "Propiedades físicas y de bloque", physicalDescription: "Comportamiento físico de bloques y recursos del mundo.", hardness: "Dureza", explosionResistance: "Resistencia a explosiones", friction: "Fricción", speedFactor: "Factor de velocidad", jumpFactor: "Factor de salto", lightLevel: "Nivel de luz", requiresCorrectTool: "Requiere herramienta correcta", randomTicks: "Ticks aleatorios", replaceable: "Reemplazable", air: "Tratado como aire",
    toolTitle: "Propiedades de herramienta", toolDescription: "Minería, combate, durabilidad, nivel, reparación y encantamiento.", toolType: "Tipo de herramienta", tier: "Nivel de herramienta", repairTag: "Tag de reparación", durability: "Durabilidad", miningSpeed: "Velocidad de minería", attackDamage: "Daño de ataque", attackSpeed: "Velocidad de ataque", enchantability: "Encantabilidad", harvestLevel: "Nivel de recolección",
    renderTitle: "Propiedades de renderizado", renderDescription: "Describe el renderizador, modelo y transformación independientemente de la vista previa.", renderMode: "Modo de renderizado", unset: "Sin definir", model: "Modelo", modelResourceId: "ID de recurso del modelo", renderer: "ID del renderizador", scale: "Escala", rotation: "Rotación (X/Y/Z)", translation: "Traslación (X/Y/Z)",
    fluidTitle: "Propiedades de fluido", fluidDescription: "Propiedades físicas y visuales de los fluidos.", chemicalTitle: "Propiedades químicas", chemicalDescription: "Propiedades de gases, lodos, pigmentos y otras sustancias químicas.", density: "Densidad", viscosity: "Viscosidad", temperature: "Temperatura", luminosity: "Luminosidad", tint: "Color de tinte", gaseous: "Gaseoso",
    extensionTitle: "Datos de extensión del mod", extensionDescription: "Añade propiedades futuras o específicas del mod como un objeto JSON.", applyExtensions: "Aplicar JSON de extensión", extensionInvalid: "Introduce un objeto JSON válido sin nombres de secciones reservados.",
  },
  contentTranslation: {
    ...en.contentTranslation,
    loading: "Resolviendo el idioma…", aiBadge: "Traducido por IA", humanCorrectedBadge: "Corregido manualmente", showingFallback: "Mostrando contenido alternativo en {locale}",
    freeInProgress: "Traducción por IA en curso · no usa el cupo diario", paidInProgress: "Traducción por IA en curso · usa el cupo diario",
    paidExplanation: "Traduce este contenido a {locale} y guárdalo. Esta acción usa tu cupo diario de tokens de IA.", translate: "Traducir", requesting: "Solicitando…", loginToTranslate: "Inicia sesión para traducir", noPermission: "Traducción no disponible", readOnly: "La versión {locale} es solo para traducción por IA y no se puede editar manualmente.", failed: "Falló la traducción por IA. Inténtalo de nuevo más tarde.",
  },
  contentLanguage: {
    ...en.contentLanguage,
    title: "Preferencias de idioma del contenido", description: "Elige el primer y segundo idioma para el contenido localizado. Los idiomas admitidos se pueden editar; los demás idiomas BCP 47 usan traducciones de IA guardadas.",
    primary: "Primer idioma del contenido", primaryHint: "El sitio busca primero este idioma; uno no admitido funciona como destino de traducción de solo lectura.", secondary: "Segundo idioma del contenido", secondaryHint: "Se usa cuando el primer idioma no está disponible.",
    chineseFallbackHint: "El chino simplificado y tradicional se sustituyen entre sí antes que el inglés.", editablePrimary: "Idioma editable", translationOnlyPrimary: "Solo traducción", save: "Guardar idiomas", saved: "Preferencias de idioma guardadas.", required: "Introduce ambos idiomas del contenido.", loadFailed: "No se pudieron cargar las preferencias de idioma.", saveFailed: "No se pudieron guardar las preferencias de idioma.",
  },
  admin: { ...en.admin, title: "Consola admin", i18n: "Gestión multilingüe", translationManager: "Gestión de traducciones" },
};
es.mods = { ...es.mods, detail: { ...es.mods.detail, downloads: {
  ...en.mods.detail.downloads,
  title: "Archivos del proyecto", subtitle: "Elige una versión de Minecraft y un cargador, y descarga directamente desde Mcmods-cn, Modrinth o CurseForge sin abrir la página externa del proyecto.",
  minecraftVersion: "Versión de Minecraft", all: "Todas", loader: "Cargador", allLoaders: "Todos los cargadores", source: "Fuente de descarga", allSources: "Todas las fuentes", externalSources: "Fuentes externas",
  noFiles: "Ningún archivo coincide con los filtros.", loadFailed: "No se pudieron cargar los archivos.", downloadFailed: "No se pudo preparar la descarga.", downloadCount: "{count} descargas", updated: "Actualizado el {date}", preparing: "Preparando…", download: "Descargar",
  deleteConfirm: "¿Eliminar {name} de las descargas del sitio?", deleteFailed: "No se pudo eliminar el archivo.", providerUnavailable: "{source} no está disponible temporalmente.",
  uploadTitle: "Subir un archivo de publicación", uploadDescription: "Sube un archivo de publicación de confianza para {project}. Esta acción requiere el permiso de subida específico del proyecto.", projectFile: "Archivo de publicación ({formats})", displayName: "Nombre visible", versionName: "Versión del proyecto", gameVersions: "Versiones de Minecraft", loaders: "Cargadores", releaseChannel: "Canal de publicación",
  channels: { release: "Estable", beta: "Beta", alpha: "Alfa" }, unsupportedFileFormat: "Selecciona un archivo compatible: {formats}.", metadataRequired: "La versión del proyecto, la versión de Minecraft y el cargador son obligatorios.", upload: "Subir archivo", uploading: "Subiendo…", uploaded: "El archivo del sitio se ha publicado.", uploadFailed: "No se pudo subir el archivo.",
} } };
export default es;
