import en from "./en";
const fr = {
  ...en,
  common: { ...en.common, home: "Accueil", login: "Connexion", register: "Inscription", logout: "Déconnexion", admin: "Admin", save: "Enregistrer", delete: "Supprimer", language: "Langue" },
  home: { ...en.home, title: "Navigation des ressources" },
  skins: { ...en.skins, title: "Bibliothèque de skins", subtitle: "Parcourez et équipez des skins et capes de la communauté sur vos profils de joueur.", upload: "Importer une apparence", kindSkin: "Skin", kindCape: "Cape", playerProfiles: "Profils de joueur", wardrobe: "Ma garde-robe", launcherLogin: "Connexion via lanceur tiers", saveProfile: "Enregistrer le profil", deleteProfile: "Supprimer le profil", visibilityPublic: "Public", visibilityUnlisted: "Non répertorié", visibilityPrivate: "Privé", copyAddress: "Copier", copied: "Copié" },
  assetEditor: { ...en.assetEditor, back: "Retour aux détails", skinTitle: "Modifier le skin", blueprintTitle: "Modifier le plan", submit: "Soumettre les modifications", name: "Nom", introduction: "Présentation", tags: "Étiquettes", visibility: "Visibilité", visibilityPublic: "Public", visibilityUnlisted: "Non répertorié", visibilityPrivate: "Privé", armModel: "Modèle des bras", modelClassic: "Classique", modelSlim: "Fin", reason: "Résumé des modifications", loginRequired: "Connectez-vous avant de modifier.", submitted: "Modifications soumises. Les versions linguistiques soumises à validation seront publiées après approbation.", saveFailed: "Échec de l’enregistrement des modifications.", loadFailed: "Échec du chargement des données d’édition.", defaultReason: "Modification du contenu localisé" },
  mods: { ...en.mods, submission: { ...en.mods.submission, defaultLocale: "Langue de contenu par défaut", galleryUploadFailed: "Échec de l’envoi de l’image de galerie.", modIds: { title: "Identifiants du mod", hint: "Enregistrez les identifiants actuels et historiques selon la version de Minecraft. L’identifiant principal sert à l’affichage canonique et tous pointent vers la même ressource globale.", add: "Ajouter un identifiant", identifier: "Identifiant du mod", minimumVersion: "Version minimale", maximumVersion: "Version maximale", minimumPlaceholder: "Par exemple 1.18", maximumPlaceholder: "Vide signifie sans limite", primary: "Identifiant principal" }, sections: { ...en.mods.submission.sections, gallery: "Galerie", galleryHint: "Les images sont envoyées directement vers l’OSS privé et sont validées avec cette révision complète du mod." }, actions: { ...en.mods.submission.actions, uploadGallery: "Ajouter des images à la galerie", uploadingGallery: "Envoi en cours…" } } },
  catalogEditor: { ...en.catalogEditor },
  resourceEditor: {
    ...en.resourceEditor,
    catalogShort: "Ressources", catalogTitle: "Catalogue global des ressources", catalogDescription: "Parcourez et gérez manuellement les objets, blocs, fluides, produits chimiques et autres ressources du jeu. L’importation reste une aide.",
    search: "Rechercher des ressources", searchPlaceholder: "Nom localisé ou ID de ressource", allKinds: "Tous les types", allRegistries: "Tous les espaces de noms", empty: "Aucune ressource correspondante.", globalResource: "Ressource globale",
    create: "Créer une ressource", edit: "Modifier la ressource", back: "Retour aux ressources", description: "Gérez l’identité stable, les contenus multilingues, les images OSS privées et les propriétés structurées. Chaque modification est contrôlée et journalisée.",
    validationRequired: "Saisissez le type, l’ID canonique et un nom dans la langue par défaut.", archiveConfirm: "Archiver cette ressource ?", imageOnly: "Sélectionnez une image pour l’icône ou l’aperçu.", uploadFailed: "Échec de l’envoi de l’image.",
    kind: "Type de ressource", ownerMod: "ID de site du mod propriétaire", ownerModPlaceholder: "Facultatif, par ex. create", assetsTitle: "Visuels de la ressource", assetsDescription: "Le navigateur envoie les images directement vers l’OSS privé ; les ID de fichier sont contrôlés avec cette révision.", icon: "Icône", render: "Image rendue", iconEmpty: "Aucune icône", renderEmpty: "Aucune image rendue", upload: "Envoyer une image", uploading: "Envoi…", assetRecords: "Fichiers liés", iconFileId: "ID du fichier d’icône", renderFileId: "ID du fichier rendu",
    physicalTitle: "Propriétés physiques et de bloc", physicalDescription: "Comportement physique des blocs et des ressources du monde.", hardness: "Dureté", explosionResistance: "Résistance aux explosions", friction: "Friction", speedFactor: "Facteur de vitesse", jumpFactor: "Facteur de saut", lightLevel: "Niveau de lumière", requiresCorrectTool: "Outil approprié requis", randomTicks: "Ticks aléatoires", replaceable: "Remplaçable", air: "Traité comme de l’air",
    toolTitle: "Propriétés de l’outil", toolDescription: "Minage, combat, durabilité, niveau, réparation et enchantement.", toolType: "Type d’outil", tier: "Niveau d’outil", repairTag: "Tag de réparation", durability: "Durabilité", miningSpeed: "Vitesse de minage", attackDamage: "Dégâts d’attaque", attackSpeed: "Vitesse d’attaque", enchantability: "Enchantabilité", harvestLevel: "Niveau de récolte",
    renderTitle: "Propriétés de rendu", renderDescription: "Décrivez le moteur de rendu, le modèle et la transformation indépendamment de l’aperçu.", renderMode: "Mode de rendu", unset: "Non défini", model: "Modèle", modelResourceId: "ID de ressource du modèle", renderer: "ID du moteur de rendu", scale: "Échelle", rotation: "Rotation (X/Y/Z)", translation: "Translation (X/Y/Z)",
    fluidTitle: "Propriétés du fluide", fluidDescription: "Propriétés physiques et visuelles des fluides.", chemicalTitle: "Propriétés chimiques", chemicalDescription: "Propriétés des gaz, boues, pigments et autres produits chimiques.", density: "Densité", viscosity: "Viscosité", temperature: "Température", luminosity: "Luminosité", tint: "Couleur de teinte", gaseous: "Gazeux",
    extensionTitle: "Données d’extension du mod", extensionDescription: "Ajoutez les propriétés futures ou spécifiques au mod sous forme d’objet JSON.", applyExtensions: "Appliquer le JSON", extensionInvalid: "Saisissez un objet JSON valide sans noms de sections réservés.",
  },
  contentTranslation: {
    ...en.contentTranslation,
    loading: "Résolution de la langue…", aiBadge: "Traduit par IA", humanCorrectedBadge: "Corrigé manuellement", showingFallback: "Affichage du contenu de repli en {locale}",
    freeInProgress: "Traduction IA en cours · sans utiliser le quota quotidien", paidInProgress: "Traduction IA en cours · utilise le quota quotidien",
    paidExplanation: "Traduire ce contenu en {locale} et l’enregistrer. Cette action utilise votre quota quotidien de jetons IA.", translate: "Traduire", requesting: "Demande…", loginToTranslate: "Se connecter pour traduire", noPermission: "Traduction indisponible", readOnly: "La version {locale} est réservée à la traduction IA et n’est pas modifiable.", failed: "Échec de la traduction IA. Réessayez plus tard.",
  },
  contentLanguage: {
    ...en.contentLanguage,
    title: "Préférences de langue du contenu", description: "Choisissez les première et deuxième langues des contenus localisés. Les langues prises en charge sont modifiables ; les autres langues BCP 47 utilisent des traductions IA enregistrées.",
    primary: "Première langue du contenu", primaryHint: "Le site recherche d’abord cette langue ; une langue non prise en charge reste une cible de traduction en lecture seule.", secondary: "Deuxième langue du contenu", secondaryHint: "Utilisée lorsque la première langue n’est pas disponible.",
    chineseFallbackHint: "Le chinois simplifié et traditionnel se remplacent mutuellement avant l’anglais.", editablePrimary: "Langue modifiable", translationOnlyPrimary: "Traduction uniquement", save: "Enregistrer les langues", saved: "Préférences de langue enregistrées.", required: "Saisissez les deux langues du contenu.", loadFailed: "Impossible de charger les préférences de langue.", saveFailed: "Impossible d’enregistrer les préférences de langue.",
  },
  admin: { ...en.admin, title: "Console admin", i18n: "Gestion multilingue", translationManager: "Gestion des traductions" },
};
fr.mods = { ...fr.mods, detail: { ...fr.mods.detail, downloads: {
  ...en.mods.detail.downloads,
  title: "Fichiers du projet", subtitle: "Choisissez une version de Minecraft et un chargeur, puis téléchargez directement depuis Mcmods-cn, Modrinth ou CurseForge sans ouvrir la page externe du projet.",
  minecraftVersion: "Version de Minecraft", all: "Toutes", loader: "Chargeur", allLoaders: "Tous les chargeurs", source: "Source", allSources: "Toutes les sources", externalSources: "Sources externes",
  noFiles: "Aucun fichier ne correspond aux filtres.", loadFailed: "Impossible de charger les fichiers du projet.", downloadFailed: "Impossible de préparer le téléchargement.", downloadCount: "{count} téléchargements", updated: "Mis à jour le {date}", preparing: "Préparation…", download: "Télécharger",
  deleteConfirm: "Supprimer {name} des téléchargements du site ?", deleteFailed: "Impossible de supprimer le fichier.", providerUnavailable: "{source} est temporairement indisponible.",
  uploadTitle: "Importer un JAR sur le site", uploadDescription: "Importez un JAR fiable pour {project}. Cette action exige l’autorisation d’import propre au projet.", jarFile: "Fichier JAR", displayName: "Nom affiché", versionName: "Version du mod", gameVersions: "Versions de Minecraft", loaders: "Chargeurs", releaseChannel: "Canal de publication",
  channels: { release: "Stable", beta: "Bêta", alpha: "Alpha" }, jarOnly: "Choisissez un fichier .jar.", metadataRequired: "La version du mod, la version de Minecraft et le chargeur sont requis.", upload: "Importer le fichier", uploading: "Import en cours…", uploaded: "Le fichier du site a été publié.", uploadFailed: "Échec de l’import du fichier.",
} } };
export default fr;
