import en from "./en-US";
const ru = {
  ...en,
  common: { ...en.common, home: "Главная", login: "Войти", register: "Регистрация", logout: "Выйти", admin: "Админ", save: "Сохранить", delete: "Удалить", language: "Язык" },
  home: { ...en.home, title: "Навигация по ресурсам" },
  skins: { ...en.skins, title: "Библиотека скинов", subtitle: "Просматривайте и назначайте скины и плащи сообщества своим игровым профилям.", upload: "Загрузить внешний вид", kindSkin: "Скин", kindCape: "Плащ", playerProfiles: "Профили игроков", wardrobe: "Мой гардероб", launcherLogin: "Вход через сторонний лаунчер", saveProfile: "Сохранить профиль", deleteProfile: "Удалить профиль", visibilityPublic: "Публичный", visibilityUnlisted: "По ссылке", visibilityPrivate: "Приватный", copyAddress: "Копировать", copied: "Скопировано" },
  assetEditor: { ...en.assetEditor, back: "Назад к подробностям", skinTitle: "Редактировать скин", blueprintTitle: "Редактировать чертёж", submit: "Отправить изменения", name: "Название", introduction: "Описание", tags: "Теги", visibility: "Видимость", visibilityPublic: "Публичный", visibilityUnlisted: "По ссылке", visibilityPrivate: "Приватный", armModel: "Модель рук", modelClassic: "Классическая", modelSlim: "Тонкая", reason: "Описание изменений", loginRequired: "Войдите перед редактированием.", submitted: "Изменения отправлены. Языковые версии, требующие проверки, будут опубликованы после одобрения.", saveFailed: "Не удалось сохранить изменения.", loadFailed: "Не удалось загрузить данные редактора.", defaultReason: "Изменение локализованного содержимого" },
  mods: { ...en.mods, submission: { ...en.mods.submission, defaultLocale: "Язык содержимого по умолчанию", galleryUploadFailed: "Не удалось загрузить изображение галереи.", modIds: { title: "ID мода", hint: "Для разных версий Minecraft можно зарегистрировать текущие и прежние ID. Основной ID используется для канонического отображения, а все ID указывают на один глобальный ресурс.", add: "Добавить ID", identifier: "ID мода", minimumVersion: "Минимальная версия", maximumVersion: "Максимальная версия", minimumPlaceholder: "Например, 1.18", maximumPlaceholder: "Пусто — без ограничения", primary: "Основной ID" }, sections: { ...en.mods.submission.sections, gallery: "Галерея", galleryHint: "Изображения загружаются напрямую в приватное OSS и проверяются вместе с полной редакцией мода." }, actions: { ...en.mods.submission.actions, uploadGallery: "Загрузить изображения галереи", uploadingGallery: "Загрузка…" } } },
  catalogEditor: { ...en.catalogEditor },
  modContent: { ...en.modContent, templates: { ...en.modContent.templates, loot_table: "Таблицы добычи", game_setting: "Настройки игры" } },
  resourceEditor: {
    ...en.resourceEditor,
    catalogShort: "Ресурсы", catalogTitle: "Глобальный каталог ресурсов", catalogDescription: "Просматривайте и вручную редактируйте предметы, блоки, жидкости, химикаты и другие игровые ресурсы. Импорт служит только вспомогательным средством.",
    search: "Поиск ресурсов", searchPlaceholder: "Локализованное имя или ID ресурса", allKinds: "Все типы", allRegistries: "Все пространства имён", empty: "Подходящих ресурсов нет.", globalResource: "Глобальный ресурс",
    create: "Создать ресурс", edit: "Редактировать ресурс", back: "Назад к ресурсам", description: "Управляйте стабильным ID, многоязычным содержимым, приватными OSS-изображениями и структурированными свойствами. Каждое изменение проходит проверку и записывается в историю.",
    validationRequired: "Укажите тип, канонический ID и имя на языке по умолчанию.", archiveConfirm: "Архивировать этот ресурс?", imageOnly: "Для значка или рендера выберите изображение.", uploadFailed: "Не удалось загрузить изображение.",
    kind: "Тип ресурса", ownerMod: "Внутренний ID мода-владельца", ownerModPlaceholder: "Необязательно, например create", assetsTitle: "Изображения ресурса", assetsDescription: "Браузер напрямую загружает изображения в приватный OSS; ID файлов проверяются вместе с этой редакцией.", icon: "Значок", render: "Рендер", iconEmpty: "Значок не загружен", renderEmpty: "Рендер не загружен", upload: "Загрузить изображение", uploading: "Загрузка…", assetRecords: "Связанные файлы", iconFileId: "ID файла значка", renderFileId: "ID файла рендера",
    physicalTitle: "Физические свойства и свойства блока", physicalDescription: "Физическое поведение блоков и ресурсов мира.", hardness: "Твёрдость", explosionResistance: "Взрывоустойчивость", friction: "Трение", speedFactor: "Множитель скорости", jumpFactor: "Множитель прыжка", lightLevel: "Уровень света", requiresCorrectTool: "Нужен правильный инструмент", randomTicks: "Случайные тики", replaceable: "Заменяемый", air: "Считать воздухом",
    toolTitle: "Свойства инструмента", toolDescription: "Добыча, бой, прочность, уровень, ремонт и зачарование.", toolType: "Тип инструмента", tier: "Уровень инструмента", repairTag: "Тег материала ремонта", durability: "Прочность", miningSpeed: "Скорость добычи", attackDamage: "Урон", attackSpeed: "Скорость атаки", enchantability: "Зачаровываемость", harvestLevel: "Уровень добычи",
    renderTitle: "Свойства рендера", renderDescription: "Опишите рендерер, модель и преобразования отдельно от изображения предпросмотра.", renderMode: "Режим рендера", unset: "Не задано", model: "Модель", modelResourceId: "ID ресурса модели", renderer: "ID рендерера", scale: "Масштаб", rotation: "Вращение (X/Y/Z)", translation: "Смещение (X/Y/Z)",
    fluidTitle: "Свойства жидкости", fluidDescription: "Физические и визуальные свойства жидкостей.", chemicalTitle: "Химические свойства", chemicalDescription: "Свойства газов, суспензий, пигментов и других химикатов.", density: "Плотность", viscosity: "Вязкость", temperature: "Температура", luminosity: "Свечение", tint: "Цвет", gaseous: "Газообразный",
    extensionTitle: "Данные расширения мода", extensionDescription: "Добавьте будущие или специфичные для мода свойства объектом JSON.", applyExtensions: "Применить JSON", extensionInvalid: "Введите корректный объект JSON без зарезервированных имён разделов.",
  },
  contentTranslation: {
    ...en.contentTranslation,
    loading: "Определение языка содержимого…", aiBadge: "Переведено ИИ", humanCorrectedBadge: "Исправлено вручную", showingFallback: "Показан резервный текст на языке {locale}",
    freeInProgress: "ИИ переводит · дневной лимит токенов не расходуется", paidInProgress: "ИИ переводит · расходуется дневной лимит токенов",
    paidExplanation: "Перевести содержимое на язык {locale} и сохранить. Операция расходует дневной лимит токенов ИИ.", translate: "Перевести", requesting: "Запрос…", loginToTranslate: "Войдите для перевода", noPermission: "Перевод недоступен", readOnly: "Версия {locale} доступна только для перевода ИИ и не редактируется вручную.", failed: "Не удалось выполнить перевод ИИ. Повторите попытку позже.",
  },
  contentLanguage: {
    ...en.contentLanguage,
    title: "Языки содержимого", description: "Выберите первый и второй языки локализованного содержимого. Поддерживаемые языки можно редактировать; прочие языки BCP 47 используют сохранённые переводы ИИ.",
    primary: "Первый язык содержимого", primaryHint: "Сайт сначала ищет этот язык; неподдерживаемый язык доступен как цель перевода только для чтения.", secondary: "Второй язык содержимого", secondaryHint: "Используется, если версия на первом языке отсутствует.",
    chineseFallbackHint: "Упрощённый и традиционный китайский подменяют друг друга до перехода к английскому.", editablePrimary: "Редактируемый язык", translationOnlyPrimary: "Только перевод", save: "Сохранить языки", saved: "Языковые настройки сохранены.", required: "Укажите первый и второй языки.", loadFailed: "Не удалось загрузить языковые настройки.", saveFailed: "Не удалось сохранить языковые настройки.",
  },
  admin: { ...en.admin, title: "Панель администрирования", i18n: "Управление языками", translationManager: "Управление переводами" },
};
ru.mods = { ...ru.mods, detail: { ...ru.mods.detail, downloads: {
  ...en.mods.detail.downloads,
  title: "Файлы проекта", subtitle: "Выберите версию Minecraft и загрузчик, затем скачайте файл напрямую с Mcmods-cn, Modrinth или CurseForge без перехода на внешнюю страницу проекта.",
  minecraftVersion: "Версия Minecraft", all: "Все", loader: "Загрузчик", allLoaders: "Все загрузчики", source: "Источник", allSources: "Все источники", externalSources: "Внешние источники",
  noFiles: "Нет файлов, соответствующих фильтрам.", loadFailed: "Не удалось загрузить файлы проекта.", downloadFailed: "Не удалось подготовить скачивание.", downloadCount: "Скачиваний: {count}", updated: "Обновлено {date}", preparing: "Подготовка…", download: "Скачать",
  deleteConfirm: "Удалить {name} из загрузок сайта?", deleteFailed: "Не удалось удалить файл проекта.", providerUnavailable: "{source} временно недоступен.",
  uploadTitle: "Загрузить JAR на сайт", uploadDescription: "Загрузите доверенный JAR для {project}. Требуется отдельное разрешение проекта на загрузку файлов.", jarFile: "Файл JAR", displayName: "Отображаемое имя", versionName: "Версия мода", gameVersions: "Версии Minecraft", loaders: "Загрузчики", releaseChannel: "Канал выпуска",
  channels: { release: "Релиз", beta: "Бета", alpha: "Альфа" }, jarOnly: "Выберите файл .jar.", metadataRequired: "Необходимо указать версию мода, версию Minecraft и загрузчик.", upload: "Загрузить файл", uploading: "Загрузка…", uploaded: "Файл сайта опубликован.", uploadFailed: "Не удалось загрузить файл.",
} } };
export default ru;
